source 'http://rubygems.org'
ruby '2.3.1'
gem 'rails', '4.1.2'
gem 'sqlite3', '~> 1.3.6'
gem 'uglifier', '>= 1.3.0'
gem 'jquery-rails'
gem 'jbuilder', '~> 2.0'
gem 'activerecord', '4.1.2'
gem 'bootstrap', '~> 4.0.0'
gem 'haml-rails'
gem 'mini_racer'
gem 'geocoder'
group :development, :test do
  gem 'pry-rails'
  gem 'pry-rescue'
end
